### ISSUE TITLE
RuntimeError: main thread is not in main loop

### ISSUE THREAD

**Issue by gnoqui** [AR2000AR/CupChat#22]
##Error message or description

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Gwenaël\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "F:\CupChat\client.py", line 615, in run
    frame_message=Frame(cadre_history).pack(side=RIGHT)
  File "C:\Users\Gwenaël\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2738, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "C:\Users\Gwenaël\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 2293, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
RuntimeError: main thread is not in main loop

##What is supposed to append

Show widget in the mainthread with second thread

**Comment by AR2000AR** [comment]
#26
